<Project>
    <ItemGroup>
        <PackageReference Update="Riok.Mapperly" PrivateAssets="all" />
        <PackageReference Include="Roslynator.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Roslynator.Formatting.Analyzers" PrivateAssets="all" />
        <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" />
    </ItemGroup>
</Project>
