image:
  repository: ghcr.io/panixida-templates/dotnet-backend-template/api
  tag: development-193

migrations:
  image:
    repository: ghcr.io/panixida-templates/dotnet-backend-template/ef-migrator
    tag: development-193
