// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PANiXiDA.TacticalHeroes.Compendium.Infrastructure.Persistence.Core;

#nullable disable

namespace PANiXiDA.TacticalHeroes.Compendium.Infrastructure.Persistence.Core.Migrations
{
    [DbContext(typeof(CompendiumWriteDbContext))]
    partial class CompendiumWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compendium")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseHiLo(modelBuilder, "EntityFrameworkHiLoSequence");

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("PANiXiDA.TacticalHeroes.Compendium.Domain.Factions.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("pk_factions");

                    b.ToTable("factions", "compendium");
                });

            modelBuilder.Entity("PANiXiDA.TacticalHeroes.Compendium.Domain.Units.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<int>("Luck")
                        .HasColumnType("integer")
                        .HasColumnName("luck");

                    b.Property<int>("Morale")
                        .HasColumnType("integer")
                        .HasColumnName("morale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(2);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stats", "PANiXiDA.TacticalHeroes.Compendium.Domain.Units.Unit.Stats#UnitCombatStats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Attack")
                                .HasColumnType("integer")
                                .HasColumnName("stats_attack");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer")
                                .HasColumnName("stats_defense");

                            b1.Property<int>("Health")
                                .HasColumnType("integer")
                                .HasColumnName("stats_health");

                            b1.Property<double>("Initiative")
                                .HasColumnType("double precision")
                                .HasColumnName("stats_initiative");

                            b1.Property<int>("MaximumDamage")
                                .HasColumnType("integer")
                                .HasColumnName("stats_maximum_damage");

                            b1.Property<int>("MinimumDamage")
                                .HasColumnType("integer")
                                .HasColumnName("stats_minimum_damage");

                            b1.Property<int?>("RangedAttackRange")
                                .HasColumnType("integer")
                                .HasColumnName("stats_ranged_attack_range");

                            b1.Property<int?>("Shots")
                                .HasColumnType("integer")
                                .HasColumnName("stats_shots");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer")
                                .HasColumnName("stats_speed");
                        });

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("FactionId")
                        .HasDatabaseName("ix_units_faction_id");

                    b.ToTable("units", "compendium");
                });

            modelBuilder.Entity("PANiXiDA.TacticalHeroes.Compendium.Domain.Units.Unit", b =>
                {
                    b.HasOne("PANiXiDA.TacticalHeroes.Compendium.Domain.Factions.Faction", null)
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_factions_faction_id");
                });
#pragma warning restore 612, 618
        }
    }
}
