externalSecrets:
  openbao:
    role: tactical-heroes-api-development
  app:
    remoteKey: applications/tactical-heroes-api/development

gateway:
  host: dev.api.tactical-heroes.panixida.ru
  httpsSectionName: api-dev-tactical-heroes-https
