replicaCount: 2

env:
  values:
    ASPNETCORE_ENVIRONMENT: Production
    DOTNET_ENVIRONMENT: Production
    OTEL_SERVICE_NAME: tactical-heroes-api-production
    Identity__Provider__Issuer: https://api.tactical-heroes.panixida.ru/

externalSecrets:
  openbao:
    role: tactical-heroes-api-production
  app:
    remoteKey: applications/tactical-heroes-api/production

gateway:
  host: api.tactical-heroes.panixida.ru
  httpsSectionName: api-tactical-heroes-https
