replicaCount: 2

externalSecrets:
  openbao:
    role: tactical-heroes-api-production
  app:
    remoteKey: applications/tactical-heroes-api/production

env:
  values:
    OAuthSpa__LoginUrl: https://tactical-heroes.panixida.ru/login

gateway:
  host: api.tactical-heroes.panixida.ru
  httpsSectionName: api-tactical-heroes-https
