<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PANiXiDA.TacticalHeroes.FileManager.Application\PANiXiDA.TacticalHeroes.FileManager.Application.csproj" />
        <ProjectReference Include="..\PANiXiDA.TacticalHeroes.FileManager.Contracts\PANiXiDA.TacticalHeroes.FileManager.Contracts.csproj" />
        <ProjectReference Include="..\PANiXiDA.TacticalHeroes.FileManager.Domain\PANiXiDA.TacticalHeroes.FileManager.Domain.csproj" />
    </ItemGroup>
</Project>
